// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `backup_plaintext`, `build_backup_tags`, `build_weight_tags`, `bundle_from_keys`, `entry_method`, `format_weight`, `iso8601`, `parse_proxy_url`, `send_event_counting`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BackupEntryJson`, `HakariClient`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Generate a brand-new keypair.
Future<KeyBundle> generateKeys() => RustLib.instance.api.crateApiGenerateKeys();

/// Derive key material from an existing secret (nsec1... bech32 or 64-char hex).
Future<KeyBundle> deriveKeys({required String nsecOrHex}) =>
    RustLib.instance.api.crateApiDeriveKeys(nsecOrHex: nsecOrHex);

/// (Re)initialize the global Nostr client. Disconnects and replaces any
/// existing client. Returns the hex public key of the active identity.
Future<String> initClient({
  required ClientMode mode,
  required List<String> relays,
  required TorModeFfi tor,
}) => RustLib.instance.api.crateApiInitClient(
  mode: mode,
  relays: relays,
  tor: tor,
);

/// Disconnect and drop the global client.
Future<void> disposeClient() => RustLib.instance.api.crateApiDisposeClient();

/// Per-relay connection states of the current client.
Future<List<RelayStatusFfi>> relayStatuses() =>
    RustLib.instance.api.crateApiRelayStatuses();

/// Build the unsigned kind-1351 weight event JSON (NIP-01 shape, id included)
/// for external signing (Amber / NIP-55).
///
/// When [content_override] is provided it is used verbatim (Dart passes the
/// NIP-44 ciphertext obtained from Amber); otherwise the plain weight string.
Future<String> buildUnsignedWeightEvent({
  required FfiWeightEntry entry,
  required String pubkeyHex,
  String? contentOverride,
  required bool encrypted,
}) => RustLib.instance.api.crateApiBuildUnsignedWeightEvent(
  entry: entry,
  pubkeyHex: pubkeyHex,
  contentOverride: contentOverride,
  encrypted: encrypted,
);

/// Build the unsigned kind-30078 backup event JSON for external signing.
/// [encrypted_content] must be the NIP-44 self-encrypted backup JSON
/// (see BackupEntryJson) produced by the signer.
Future<String> buildUnsignedBackupEvent({
  required FfiWeightEntry entry,
  required String pubkeyHex,
  required String encryptedContent,
}) => RustLib.instance.api.crateApiBuildUnsignedBackupEvent(
  entry: entry,
  pubkeyHex: pubkeyHex,
  encryptedContent: encryptedContent,
);

/// Build the unsigned kind-30078 wellness backup event JSON for external
/// signing. [day_key] is the calendar day (`yyyy-MM-dd`);
/// [encrypted_content] must be the NIP-44 self-encrypted wellness JSON.
/// Parameterized-replaceable: one event per day, updates replace.
Future<String> buildUnsignedWellnessEvent({
  required String pubkeyHex,
  required String dayKey,
  required String encryptedContent,
}) => RustLib.instance.api.crateApiBuildUnsignedWellnessEvent(
  pubkeyHex: pubkeyHex,
  dayKey: dayKey,
  encryptedContent: encryptedContent,
);

/// Publish one measurement as BOTH a kind-1351 weight event (interop) and a
/// kind-30078 encrypted full-entry backup (lossless restore).
///
/// SecretKey mode only. When [encrypt] is true the 1351 content is NIP-44
/// self-encrypted; the 30078 backup content is ALWAYS encrypted.
Future<SendResultFfi> publishWeightEntry({
  required FfiWeightEntry entry,
  required bool encrypt,
}) => RustLib.instance.api.crateApiPublishWeightEntry(
  entry: entry,
  encrypt: encrypt,
);

/// Verify and publish an externally signed event (Amber flow).
Future<SendResultFfi> publishSignedEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiPublishSignedEvent(eventJson: eventJson);

/// Fetch our own NIP-101h events: kind 1351 (weight) and kind 30078 with
/// #t=hakari-health (full-entry backups). Content is returned raw;
/// decryption happens Dart-side via SignerService.
Future<List<RawEventFfi>> fetchHealthEvents({
  required String pubkeyHex,
  PlatformInt64? sinceUnix,
}) => RustLib.instance.api.crateApiFetchHealthEvents(
  pubkeyHex: pubkeyHex,
  sinceUnix: sinceUnix,
);

/// NIP-44 encrypt with a locally held secret key.
Future<String> nip44EncryptLocal({
  required String nsec,
  required String receiverPubkeyHex,
  required String plaintext,
}) => RustLib.instance.api.crateApiNip44EncryptLocal(
  nsec: nsec,
  receiverPubkeyHex: receiverPubkeyHex,
  plaintext: plaintext,
);

/// NIP-44 decrypt with a locally held secret key.
Future<String> nip44DecryptLocal({
  required String nsec,
  required String senderPubkeyHex,
  required String ciphertext,
}) => RustLib.instance.api.crateApiNip44DecryptLocal(
  nsec: nsec,
  senderPubkeyHex: senderPubkeyHex,
  ciphertext: ciphertext,
);

/// Sign an unsigned NIP-01 event JSON with a locally held secret key.
/// Returns the full signed event JSON.
Future<String> signEventLocal({
  required String nsec,
  required String unsignedEventJson,
}) => RustLib.instance.api.crateApiSignEventLocal(
  nsec: nsec,
  unsignedEventJson: unsignedEventJson,
);

class ClientMode {
  final ClientModeKind kind;

  /// Required when [kind] is SecretKey (nsec1... bech32 or hex).
  final String? nsec;

  /// Required when [kind] is PublicKeyOnly.
  final String? pubkeyHex;

  const ClientMode({required this.kind, this.nsec, this.pubkeyHex});

  @override
  int get hashCode => kind.hashCode ^ nsec.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientMode &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          nsec == other.nsec &&
          pubkeyHex == other.pubkeyHex;
}

/// How the client is allowed to operate.
/// (Unit enum + config struct instead of an enum with fields so the
/// generated Dart code does not require the freezed package.)
enum ClientModeKind {
  /// Local-key mode: Rust holds the secret and can sign/encrypt.
  secretKey,

  /// Amber mode: signing/encryption happen in the external signer app;
  /// Rust only knows the public key.
  publicKeyOnly,
}

/// Measurement payload coming from Dart (mirrors domain WeightEntry).
class FfiWeightEntry {
  final String id;

  /// Unix seconds of the measurement.
  final PlatformInt64 recordedAtUnix;
  final double weightKg;
  final double? bodyFatPercent;
  final double? bodyWaterPercent;
  final double? muscleMassKg;
  final int? visceralFatRating;
  final double? boneMassKg;
  final int? basalMetabolicRateKcal;
  final int? metabolicAge;

  /// Dart MeasurementSource enum name: manual | bleScale | healthSync | imported
  final String source;

  const FfiWeightEntry({
    required this.id,
    required this.recordedAtUnix,
    required this.weightKg,
    this.bodyFatPercent,
    this.bodyWaterPercent,
    this.muscleMassKg,
    this.visceralFatRating,
    this.boneMassKg,
    this.basalMetabolicRateKcal,
    this.metabolicAge,
    required this.source,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      recordedAtUnix.hashCode ^
      weightKg.hashCode ^
      bodyFatPercent.hashCode ^
      bodyWaterPercent.hashCode ^
      muscleMassKg.hashCode ^
      visceralFatRating.hashCode ^
      boneMassKg.hashCode ^
      basalMetabolicRateKcal.hashCode ^
      metabolicAge.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiWeightEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          recordedAtUnix == other.recordedAtUnix &&
          weightKg == other.weightKg &&
          bodyFatPercent == other.bodyFatPercent &&
          bodyWaterPercent == other.bodyWaterPercent &&
          muscleMassKg == other.muscleMassKg &&
          visceralFatRating == other.visceralFatRating &&
          boneMassKg == other.boneMassKg &&
          basalMetabolicRateKcal == other.basalMetabolicRateKcal &&
          metabolicAge == other.metabolicAge &&
          source == other.source;
}

/// Key material derived from / for a secret key.
class KeyBundle {
  final String nsec;
  final String npub;
  final String pubkeyHex;

  const KeyBundle({
    required this.nsec,
    required this.npub,
    required this.pubkeyHex,
  });

  @override
  int get hashCode => nsec.hashCode ^ npub.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyBundle &&
          runtimeType == other.runtimeType &&
          nsec == other.nsec &&
          npub == other.npub &&
          pubkeyHex == other.pubkeyHex;
}

/// Raw relay event handed to Dart (decryption happens Dart-side via
/// SignerService so it works in both local-key and Amber modes).
class RawEventFfi {
  final String id;
  final int kind;
  final PlatformInt64 createdAt;
  final String content;
  final List<List<String>> tags;

  const RawEventFfi({
    required this.id,
    required this.kind,
    required this.createdAt,
    required this.content,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      createdAt.hashCode ^
      content.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawEventFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          createdAt == other.createdAt &&
          content == other.content &&
          tags == other.tags;
}

class RelayStatusFfi {
  final String url;

  /// One of: initialized, pending, connecting, connected, disconnected, terminated
  final String state;

  const RelayStatusFfi({required this.url, required this.state});

  @override
  int get hashCode => url.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayStatusFfi &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          state == other.state;
}

/// Result of publishing an event.
class SendResultFfi {
  /// For `publish_weight_entry` this is the kind-1351 event id (hex).
  final String eventId;
  final int successfulRelays;
  final int failedRelays;

  const SendResultFfi({
    required this.eventId,
    required this.successfulRelays,
    required this.failedRelays,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^ successfulRelays.hashCode ^ failedRelays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendResultFfi &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          successfulRelays == other.successfulRelays &&
          failedRelays == other.failedRelays;
}

class TorModeFfi {
  final TorModeKind kind;

  /// Required when [kind] is Orbot.
  final String? proxyUrl;

  const TorModeFfi({required this.kind, this.proxyUrl});

  @override
  int get hashCode => kind.hashCode ^ proxyUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorModeFfi &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          proxyUrl == other.proxyUrl;
}

/// Tor routing mode. Orbot = SOCKS5 proxy (e.g. socks5://127.0.0.1:9050).
enum TorModeKind { disabled, orbot }
