// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -926663385;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiBuildUnsignedBackupEvent({
    required FfiWeightEntry entry,
    required String pubkeyHex,
    required String encryptedContent,
  });

  Future<String> crateApiBuildUnsignedWeightEvent({
    required FfiWeightEntry entry,
    required String pubkeyHex,
    String? contentOverride,
    required bool encrypted,
  });

  Future<KeyBundle> crateApiDeriveKeys({required String nsecOrHex});

  Future<void> crateApiDisposeClient();

  Future<List<RawEventFfi>> crateApiFetchHealthEvents({
    required String pubkeyHex,
    PlatformInt64? sinceUnix,
  });

  Future<KeyBundle> crateApiGenerateKeys();

  Future<String> crateApiInitClient({
    required ClientMode mode,
    required List<String> relays,
    required TorModeFfi tor,
  });

  Future<String> crateApiNip44DecryptLocal({
    required String nsec,
    required String senderPubkeyHex,
    required String ciphertext,
  });

  Future<String> crateApiNip44EncryptLocal({
    required String nsec,
    required String receiverPubkeyHex,
    required String plaintext,
  });

  Future<SendResultFfi> crateApiPublishSignedEvent({required String eventJson});

  Future<SendResultFfi> crateApiPublishWeightEntry({
    required FfiWeightEntry entry,
    required bool encrypt,
  });

  Future<List<RelayStatusFfi>> crateApiRelayStatuses();

  Future<String> crateApiSignEventLocal({
    required String nsec,
    required String unsignedEventJson,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiBuildUnsignedBackupEvent({
    required FfiWeightEntry entry,
    required String pubkeyHex,
    required String encryptedContent,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ffi_weight_entry(entry, serializer);
          sse_encode_String(pubkeyHex, serializer);
          sse_encode_String(encryptedContent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildUnsignedBackupEventConstMeta,
        argValues: [entry, pubkeyHex, encryptedContent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildUnsignedBackupEventConstMeta =>
      const TaskConstMeta(
        debugName: "build_unsigned_backup_event",
        argNames: ["entry", "pubkeyHex", "encryptedContent"],
      );

  @override
  Future<String> crateApiBuildUnsignedWeightEvent({
    required FfiWeightEntry entry,
    required String pubkeyHex,
    String? contentOverride,
    required bool encrypted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ffi_weight_entry(entry, serializer);
          sse_encode_String(pubkeyHex, serializer);
          sse_encode_opt_String(contentOverride, serializer);
          sse_encode_bool(encrypted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildUnsignedWeightEventConstMeta,
        argValues: [entry, pubkeyHex, contentOverride, encrypted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildUnsignedWeightEventConstMeta =>
      const TaskConstMeta(
        debugName: "build_unsigned_weight_event",
        argNames: ["entry", "pubkeyHex", "contentOverride", "encrypted"],
      );

  @override
  Future<KeyBundle> crateApiDeriveKeys({required String nsecOrHex}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nsecOrHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_bundle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeriveKeysConstMeta,
        argValues: [nsecOrHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveKeysConstMeta =>
      const TaskConstMeta(debugName: "derive_keys", argNames: ["nsecOrHex"]);

  @override
  Future<void> crateApiDisposeClient() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDisposeClientConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDisposeClientConstMeta =>
      const TaskConstMeta(debugName: "dispose_client", argNames: []);

  @override
  Future<List<RawEventFfi>> crateApiFetchHealthEvents({
    required String pubkeyHex,
    PlatformInt64? sinceUnix,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pubkeyHex, serializer);
          sse_encode_opt_box_autoadd_i_64(sinceUnix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_raw_event_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchHealthEventsConstMeta,
        argValues: [pubkeyHex, sinceUnix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchHealthEventsConstMeta => const TaskConstMeta(
    debugName: "fetch_health_events",
    argNames: ["pubkeyHex", "sinceUnix"],
  );

  @override
  Future<KeyBundle> crateApiGenerateKeys() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_bundle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenerateKeysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateKeysConstMeta =>
      const TaskConstMeta(debugName: "generate_keys", argNames: []);

  @override
  Future<String> crateApiInitClient({
    required ClientMode mode,
    required List<String> relays,
    required TorModeFfi tor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_client_mode(mode, serializer);
          sse_encode_list_String(relays, serializer);
          sse_encode_box_autoadd_tor_mode_ffi(tor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitClientConstMeta,
        argValues: [mode, relays, tor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitClientConstMeta => const TaskConstMeta(
    debugName: "init_client",
    argNames: ["mode", "relays", "tor"],
  );

  @override
  Future<String> crateApiNip44DecryptLocal({
    required String nsec,
    required String senderPubkeyHex,
    required String ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nsec, serializer);
          sse_encode_String(senderPubkeyHex, serializer);
          sse_encode_String(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNip44DecryptLocalConstMeta,
        argValues: [nsec, senderPubkeyHex, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNip44DecryptLocalConstMeta => const TaskConstMeta(
    debugName: "nip44_decrypt_local",
    argNames: ["nsec", "senderPubkeyHex", "ciphertext"],
  );

  @override
  Future<String> crateApiNip44EncryptLocal({
    required String nsec,
    required String receiverPubkeyHex,
    required String plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nsec, serializer);
          sse_encode_String(receiverPubkeyHex, serializer);
          sse_encode_String(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNip44EncryptLocalConstMeta,
        argValues: [nsec, receiverPubkeyHex, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNip44EncryptLocalConstMeta => const TaskConstMeta(
    debugName: "nip44_encrypt_local",
    argNames: ["nsec", "receiverPubkeyHex", "plaintext"],
  );

  @override
  Future<SendResultFfi> crateApiPublishSignedEvent({
    required String eventJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPublishSignedEventConstMeta,
        argValues: [eventJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPublishSignedEventConstMeta => const TaskConstMeta(
    debugName: "publish_signed_event",
    argNames: ["eventJson"],
  );

  @override
  Future<SendResultFfi> crateApiPublishWeightEntry({
    required FfiWeightEntry entry,
    required bool encrypt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ffi_weight_entry(entry, serializer);
          sse_encode_bool(encrypt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPublishWeightEntryConstMeta,
        argValues: [entry, encrypt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPublishWeightEntryConstMeta => const TaskConstMeta(
    debugName: "publish_weight_entry",
    argNames: ["entry", "encrypt"],
  );

  @override
  Future<List<RelayStatusFfi>> crateApiRelayStatuses() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_relay_status_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRelayStatusesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayStatusesConstMeta =>
      const TaskConstMeta(debugName: "relay_statuses", argNames: []);

  @override
  Future<String> crateApiSignEventLocal({
    required String nsec,
    required String unsignedEventJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nsec, serializer);
          sse_encode_String(unsignedEventJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSignEventLocalConstMeta,
        argValues: [nsec, unsignedEventJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignEventLocalConstMeta => const TaskConstMeta(
    debugName: "sign_event_local",
    argNames: ["nsec", "unsignedEventJson"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ClientMode dco_decode_box_autoadd_client_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_client_mode(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfiWeightEntry dco_decode_box_autoadd_ffi_weight_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_weight_entry(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  TorModeFfi dco_decode_box_autoadd_tor_mode_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tor_mode_ffi(raw);
  }

  @protected
  ClientMode dco_decode_client_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ClientMode(
      kind: dco_decode_client_mode_kind(arr[0]),
      nsec: dco_decode_opt_String(arr[1]),
      pubkeyHex: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ClientModeKind dco_decode_client_mode_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientModeKind.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfiWeightEntry dco_decode_ffi_weight_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return FfiWeightEntry(
      id: dco_decode_String(arr[0]),
      recordedAtUnix: dco_decode_i_64(arr[1]),
      weightKg: dco_decode_f_64(arr[2]),
      bodyFatPercent: dco_decode_opt_box_autoadd_f_64(arr[3]),
      bodyWaterPercent: dco_decode_opt_box_autoadd_f_64(arr[4]),
      muscleMassKg: dco_decode_opt_box_autoadd_f_64(arr[5]),
      visceralFatRating: dco_decode_opt_box_autoadd_i_32(arr[6]),
      boneMassKg: dco_decode_opt_box_autoadd_f_64(arr[7]),
      basalMetabolicRateKcal: dco_decode_opt_box_autoadd_i_32(arr[8]),
      metabolicAge: dco_decode_opt_box_autoadd_i_32(arr[9]),
      source: dco_decode_String(arr[10]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KeyBundle dco_decode_key_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KeyBundle(
      nsec: dco_decode_String(arr[0]),
      npub: dco_decode_String(arr[1]),
      pubkeyHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RawEventFfi> dco_decode_list_raw_event_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_raw_event_ffi).toList();
  }

  @protected
  List<RelayStatusFfi> dco_decode_list_relay_status_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_relay_status_ffi).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RawEventFfi dco_decode_raw_event_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RawEventFfi(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_u_16(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
      content: dco_decode_String(arr[3]),
      tags: dco_decode_list_list_String(arr[4]),
    );
  }

  @protected
  RelayStatusFfi dco_decode_relay_status_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RelayStatusFfi(
      url: dco_decode_String(arr[0]),
      state: dco_decode_String(arr[1]),
    );
  }

  @protected
  SendResultFfi dco_decode_send_result_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SendResultFfi(
      eventId: dco_decode_String(arr[0]),
      successfulRelays: dco_decode_u_32(arr[1]),
      failedRelays: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  TorModeFfi dco_decode_tor_mode_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TorModeFfi(
      kind: dco_decode_tor_mode_kind(arr[0]),
      proxyUrl: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  TorModeKind dco_decode_tor_mode_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorModeKind.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ClientMode sse_decode_box_autoadd_client_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_client_mode(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FfiWeightEntry sse_decode_box_autoadd_ffi_weight_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_weight_entry(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  TorModeFfi sse_decode_box_autoadd_tor_mode_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tor_mode_ffi(deserializer));
  }

  @protected
  ClientMode sse_decode_client_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_client_mode_kind(deserializer);
    var var_nsec = sse_decode_opt_String(deserializer);
    var var_pubkeyHex = sse_decode_opt_String(deserializer);
    return ClientMode(kind: var_kind, nsec: var_nsec, pubkeyHex: var_pubkeyHex);
  }

  @protected
  ClientModeKind sse_decode_client_mode_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ClientModeKind.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FfiWeightEntry sse_decode_ffi_weight_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_recordedAtUnix = sse_decode_i_64(deserializer);
    var var_weightKg = sse_decode_f_64(deserializer);
    var var_bodyFatPercent = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_bodyWaterPercent = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_muscleMassKg = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_visceralFatRating = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_boneMassKg = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_basalMetabolicRateKcal = sse_decode_opt_box_autoadd_i_32(
      deserializer,
    );
    var var_metabolicAge = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_source = sse_decode_String(deserializer);
    return FfiWeightEntry(
      id: var_id,
      recordedAtUnix: var_recordedAtUnix,
      weightKg: var_weightKg,
      bodyFatPercent: var_bodyFatPercent,
      bodyWaterPercent: var_bodyWaterPercent,
      muscleMassKg: var_muscleMassKg,
      visceralFatRating: var_visceralFatRating,
      boneMassKg: var_boneMassKg,
      basalMetabolicRateKcal: var_basalMetabolicRateKcal,
      metabolicAge: var_metabolicAge,
      source: var_source,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KeyBundle sse_decode_key_bundle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nsec = sse_decode_String(deserializer);
    var var_npub = sse_decode_String(deserializer);
    var var_pubkeyHex = sse_decode_String(deserializer);
    return KeyBundle(nsec: var_nsec, npub: var_npub, pubkeyHex: var_pubkeyHex);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RawEventFfi> sse_decode_list_raw_event_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RawEventFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_raw_event_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  List<RelayStatusFfi> sse_decode_list_relay_status_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RelayStatusFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_relay_status_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RawEventFfi sse_decode_raw_event_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_u_16(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_list_String(deserializer);
    return RawEventFfi(
      id: var_id,
      kind: var_kind,
      createdAt: var_createdAt,
      content: var_content,
      tags: var_tags,
    );
  }

  @protected
  RelayStatusFfi sse_decode_relay_status_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    return RelayStatusFfi(url: var_url, state: var_state);
  }

  @protected
  SendResultFfi sse_decode_send_result_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    var var_successfulRelays = sse_decode_u_32(deserializer);
    var var_failedRelays = sse_decode_u_32(deserializer);
    return SendResultFfi(
      eventId: var_eventId,
      successfulRelays: var_successfulRelays,
      failedRelays: var_failedRelays,
    );
  }

  @protected
  TorModeFfi sse_decode_tor_mode_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_tor_mode_kind(deserializer);
    var var_proxyUrl = sse_decode_opt_String(deserializer);
    return TorModeFfi(kind: var_kind, proxyUrl: var_proxyUrl);
  }

  @protected
  TorModeKind sse_decode_tor_mode_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TorModeKind.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_client_mode(
    ClientMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_client_mode(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_weight_entry(
    FfiWeightEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_weight_entry(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tor_mode_ffi(
    TorModeFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tor_mode_ffi(self, serializer);
  }

  @protected
  void sse_encode_client_mode(ClientMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_client_mode_kind(self.kind, serializer);
    sse_encode_opt_String(self.nsec, serializer);
    sse_encode_opt_String(self.pubkeyHex, serializer);
  }

  @protected
  void sse_encode_client_mode_kind(
    ClientModeKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_ffi_weight_entry(
    FfiWeightEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.recordedAtUnix, serializer);
    sse_encode_f_64(self.weightKg, serializer);
    sse_encode_opt_box_autoadd_f_64(self.bodyFatPercent, serializer);
    sse_encode_opt_box_autoadd_f_64(self.bodyWaterPercent, serializer);
    sse_encode_opt_box_autoadd_f_64(self.muscleMassKg, serializer);
    sse_encode_opt_box_autoadd_i_32(self.visceralFatRating, serializer);
    sse_encode_opt_box_autoadd_f_64(self.boneMassKg, serializer);
    sse_encode_opt_box_autoadd_i_32(self.basalMetabolicRateKcal, serializer);
    sse_encode_opt_box_autoadd_i_32(self.metabolicAge, serializer);
    sse_encode_String(self.source, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_key_bundle(KeyBundle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nsec, serializer);
    sse_encode_String(self.npub, serializer);
    sse_encode_String(self.pubkeyHex, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_raw_event_ffi(
    List<RawEventFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_raw_event_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_relay_status_ffi(
    List<RelayStatusFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_relay_status_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_raw_event_ffi(RawEventFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_u_16(self.kind, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_list_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_relay_status_ffi(
    RelayStatusFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.state, serializer);
  }

  @protected
  void sse_encode_send_result_ffi(
    SendResultFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
    sse_encode_u_32(self.successfulRelays, serializer);
    sse_encode_u_32(self.failedRelays, serializer);
  }

  @protected
  void sse_encode_tor_mode_ffi(TorModeFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tor_mode_kind(self.kind, serializer);
    sse_encode_opt_String(self.proxyUrl, serializer);
  }

  @protected
  void sse_encode_tor_mode_kind(TorModeKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
