// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ClientMode dco_decode_box_autoadd_client_mode(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FfiWeightEntry dco_decode_box_autoadd_ffi_weight_entry(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  TorModeFfi dco_decode_box_autoadd_tor_mode_ffi(dynamic raw);

  @protected
  ClientMode dco_decode_client_mode(dynamic raw);

  @protected
  ClientModeKind dco_decode_client_mode_kind(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiWeightEntry dco_decode_ffi_weight_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyBundle dco_decode_key_bundle(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RawEventFfi> dco_decode_list_raw_event_ffi(dynamic raw);

  @protected
  List<RelayStatusFfi> dco_decode_list_relay_status_ffi(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RawEventFfi dco_decode_raw_event_ffi(dynamic raw);

  @protected
  RelayStatusFfi dco_decode_relay_status_ffi(dynamic raw);

  @protected
  SendResultFfi dco_decode_send_result_ffi(dynamic raw);

  @protected
  TorModeFfi dco_decode_tor_mode_ffi(dynamic raw);

  @protected
  TorModeKind dco_decode_tor_mode_kind(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ClientMode sse_decode_box_autoadd_client_mode(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FfiWeightEntry sse_decode_box_autoadd_ffi_weight_entry(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TorModeFfi sse_decode_box_autoadd_tor_mode_ffi(SseDeserializer deserializer);

  @protected
  ClientMode sse_decode_client_mode(SseDeserializer deserializer);

  @protected
  ClientModeKind sse_decode_client_mode_kind(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiWeightEntry sse_decode_ffi_weight_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyBundle sse_decode_key_bundle(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RawEventFfi> sse_decode_list_raw_event_ffi(SseDeserializer deserializer);

  @protected
  List<RelayStatusFfi> sse_decode_list_relay_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RawEventFfi sse_decode_raw_event_ffi(SseDeserializer deserializer);

  @protected
  RelayStatusFfi sse_decode_relay_status_ffi(SseDeserializer deserializer);

  @protected
  SendResultFfi sse_decode_send_result_ffi(SseDeserializer deserializer);

  @protected
  TorModeFfi sse_decode_tor_mode_ffi(SseDeserializer deserializer);

  @protected
  TorModeKind sse_decode_tor_mode_kind(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_client_mode(
    ClientMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_weight_entry(
    FfiWeightEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tor_mode_ffi(
    TorModeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_client_mode(ClientMode self, SseSerializer serializer);

  @protected
  void sse_encode_client_mode_kind(
    ClientModeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_weight_entry(
    FfiWeightEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_bundle(KeyBundle self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_raw_event_ffi(
    List<RawEventFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relay_status_ffi(
    List<RelayStatusFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_raw_event_ffi(RawEventFfi self, SseSerializer serializer);

  @protected
  void sse_encode_relay_status_ffi(
    RelayStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_result_ffi(SendResultFfi self, SseSerializer serializer);

  @protected
  void sse_encode_tor_mode_ffi(TorModeFfi self, SseSerializer serializer);

  @protected
  void sse_encode_tor_mode_kind(TorModeKind self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
